/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Indexed,
  IndexedInterface,
} from "../../../../../@hyperlane-xyz/core/contracts/libs/Indexed";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "deployedBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a0604052348015600f57600080fd5b5043608052608051609b61002c600039600060310152609b6000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806382ea7bfe14602d575b600080fd5b60537f000000000000000000000000000000000000000000000000000000000000000081565b60405190815260200160405180910390f3fea2646970667358221220ca519593228f9fc61797c7d7e8783d8d6c47d92b733673589d39845aec60751164736f6c63430008180033";

type IndexedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: IndexedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Indexed__factory extends ContractFactory {
  constructor(...args: IndexedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Indexed & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Indexed__factory {
    return super.connect(runner) as Indexed__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IndexedInterface {
    return new Interface(_abi) as IndexedInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Indexed {
    return new Contract(address, _abi, runner) as unknown as Indexed;
  }
}
